# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b856f56b74edb843391a0e4ed50a7409673ae5cdeb3057b57205fa7ec4de7a6df54e03398113649cdfbe673c788088fb5b84970dc6501209ce0dd3be31117aa4

test:
  secret_key_base: cea1d13a812e56f85972ac3d8a1585aee309f649818cc48476e09e4f6a54baaf643136a3a67d3d817787fc07aaac1bf03322b003f028704646962dfdd2a4d52d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
